// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum PlayerType : int {
  PLAYER_TYPE_NONE = 0,
  PLAYER_TYPE_CLIENT = 1,
  PLAYER_TYPE_LV1 = 2,
  PLAYER_TYPE_LV2 = 3,
  PLAYER_TYPE_LV3 = 4,
  PLAYER_TYPE_LV4 = 5,
  PLAYER_TYPE_DUMMY = 6,
  PlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlayerType_IsValid(int value);
constexpr PlayerType PlayerType_MIN = PLAYER_TYPE_NONE;
constexpr PlayerType PlayerType_MAX = PLAYER_TYPE_DUMMY;
constexpr int PlayerType_ARRAYSIZE = PlayerType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor();
template<typename T>
inline const std::string& PlayerType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerType_descriptor(), enum_t_value);
}
inline bool PlayerType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlayerType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerType>(
    PlayerType_descriptor(), name, value);
}
enum GetType : int {
  PLAYER_INFO = 0,
  INVENTORY_INFO = 1,
  EQUIPMENT_INFO = 2,
  GetType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GetType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GetType_IsValid(int value);
constexpr GetType GetType_MIN = PLAYER_INFO;
constexpr GetType GetType_MAX = EQUIPMENT_INFO;
constexpr int GetType_ARRAYSIZE = GetType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GetType_descriptor();
template<typename T>
inline const std::string& GetType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GetType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GetType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GetType_descriptor(), enum_t_value);
}
inline bool GetType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GetType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GetType>(
    GetType_descriptor(), name, value);
}
enum InventoryTab : int {
  INVENTORY_TAB_NONE = 0,
  EQUIP = 1,
  CONSUME = 2,
  MISC = 3,
  InventoryTab_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  InventoryTab_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool InventoryTab_IsValid(int value);
constexpr InventoryTab InventoryTab_MIN = INVENTORY_TAB_NONE;
constexpr InventoryTab InventoryTab_MAX = MISC;
constexpr int InventoryTab_ARRAYSIZE = InventoryTab_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* InventoryTab_descriptor();
template<typename T>
inline const std::string& InventoryTab_Name(T enum_t_value) {
  static_assert(::std::is_same<T, InventoryTab>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function InventoryTab_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    InventoryTab_descriptor(), enum_t_value);
}
inline bool InventoryTab_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, InventoryTab* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<InventoryTab>(
    InventoryTab_descriptor(), name, value);
}
enum EquipmentSlot : int {
  EQUIPMENTSLOT_NONE = 0,
  WEAPON = 1,
  HELMET = 2,
  TOP = 3,
  BOTTOM = 4,
  EquipmentSlot_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EquipmentSlot_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EquipmentSlot_IsValid(int value);
constexpr EquipmentSlot EquipmentSlot_MIN = EQUIPMENTSLOT_NONE;
constexpr EquipmentSlot EquipmentSlot_MAX = BOTTOM;
constexpr int EquipmentSlot_ARRAYSIZE = EquipmentSlot_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EquipmentSlot_descriptor();
template<typename T>
inline const std::string& EquipmentSlot_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EquipmentSlot>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EquipmentSlot_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EquipmentSlot_descriptor(), enum_t_value);
}
inline bool EquipmentSlot_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EquipmentSlot* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EquipmentSlot>(
    EquipmentSlot_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::PlayerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PlayerType>() {
  return ::Protocol::PlayerType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::GetType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::GetType>() {
  return ::Protocol::GetType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::InventoryTab> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::InventoryTab>() {
  return ::Protocol::InventoryTab_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EquipmentSlot> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EquipmentSlot>() {
  return ::Protocol::EquipmentSlot_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
