// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class AddPlayer;
struct AddPlayerDefaultTypeInternal;
extern AddPlayerDefaultTypeInternal _AddPlayer_default_instance_;
class Mess;
struct MessDefaultTypeInternal;
extern MessDefaultTypeInternal _Mess_default_instance_;
class Move;
struct MoveDefaultTypeInternal;
extern MoveDefaultTypeInternal _Move_default_instance_;
class Player;
struct PlayerDefaultTypeInternal;
extern PlayerDefaultTypeInternal _Player_default_instance_;
class Stat;
struct StatDefaultTypeInternal;
extern StatDefaultTypeInternal _Stat_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::AddPlayer* Arena::CreateMaybeMessage<::Protocol::AddPlayer>(Arena*);
template<> ::Protocol::Mess* Arena::CreateMaybeMessage<::Protocol::Mess>(Arena*);
template<> ::Protocol::Move* Arena::CreateMaybeMessage<::Protocol::Move>(Arena*);
template<> ::Protocol::Player* Arena::CreateMaybeMessage<::Protocol::Player>(Arena*);
template<> ::Protocol::Stat* Arena::CreateMaybeMessage<::Protocol::Stat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class Player final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Player) */ {
 public:
  inline Player() : Player(nullptr) {}
  ~Player() override;
  explicit constexpr Player(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Player(const Player& from);
  Player(Player&& from) noexcept
    : Player() {
    *this = ::std::move(from);
  }

  inline Player& operator=(const Player& from) {
    CopyFrom(from);
    return *this;
  }
  inline Player& operator=(Player&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Player& default_instance() {
    return *internal_default_instance();
  }
  static inline const Player* internal_default_instance() {
    return reinterpret_cast<const Player*>(
               &_Player_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Player& a, Player& b) {
    a.Swap(&b);
  }
  inline void Swap(Player* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Player* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Player* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Player>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Player& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Player& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Player* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Player";
  }
  protected:
  explicit Player(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayertypeFieldNumber = 1,
    kNameFieldNumber = 3,
    kIdFieldNumber = 2,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kLevelFieldNumber = 6,
    kHpFieldNumber = 7,
    kMaxhpFieldNumber = 8,
    kMpFieldNumber = 9,
    kMaxmpFieldNumber = 10,
    kExpFieldNumber = 11,
    kMaxexpFieldNumber = 12,
  };
  // repeated .Protocol.PlayerType playertype = 1;
  int playertype_size() const;
  private:
  int _internal_playertype_size() const;
  public:
  void clear_playertype();
  private:
  ::Protocol::PlayerType _internal_playertype(int index) const;
  void _internal_add_playertype(::Protocol::PlayerType value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_playertype();
  public:
  ::Protocol::PlayerType playertype(int index) const;
  void set_playertype(int index, ::Protocol::PlayerType value);
  void add_playertype(::Protocol::PlayerType value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& playertype() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_playertype();

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 id = 2;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 x = 4;
  void clear_x();
  uint64_t x() const;
  void set_x(uint64_t value);
  private:
  uint64_t _internal_x() const;
  void _internal_set_x(uint64_t value);
  public:

  // uint64 y = 5;
  void clear_y();
  uint64_t y() const;
  void set_y(uint64_t value);
  private:
  uint64_t _internal_y() const;
  void _internal_set_y(uint64_t value);
  public:

  // uint64 level = 6;
  void clear_level();
  uint64_t level() const;
  void set_level(uint64_t value);
  private:
  uint64_t _internal_level() const;
  void _internal_set_level(uint64_t value);
  public:

  // uint64 hp = 7;
  void clear_hp();
  uint64_t hp() const;
  void set_hp(uint64_t value);
  private:
  uint64_t _internal_hp() const;
  void _internal_set_hp(uint64_t value);
  public:

  // uint64 maxhp = 8;
  void clear_maxhp();
  uint64_t maxhp() const;
  void set_maxhp(uint64_t value);
  private:
  uint64_t _internal_maxhp() const;
  void _internal_set_maxhp(uint64_t value);
  public:

  // uint64 mp = 9;
  void clear_mp();
  uint64_t mp() const;
  void set_mp(uint64_t value);
  private:
  uint64_t _internal_mp() const;
  void _internal_set_mp(uint64_t value);
  public:

  // uint64 maxmp = 10;
  void clear_maxmp();
  uint64_t maxmp() const;
  void set_maxmp(uint64_t value);
  private:
  uint64_t _internal_maxmp() const;
  void _internal_set_maxmp(uint64_t value);
  public:

  // uint64 exp = 11;
  void clear_exp();
  uint64_t exp() const;
  void set_exp(uint64_t value);
  private:
  uint64_t _internal_exp() const;
  void _internal_set_exp(uint64_t value);
  public:

  // uint64 maxexp = 12;
  void clear_maxexp();
  uint64_t maxexp() const;
  void set_maxexp(uint64_t value);
  private:
  uint64_t _internal_maxexp() const;
  void _internal_set_maxexp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Player)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> playertype_;
  mutable std::atomic<int> _playertype_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  uint64_t id_;
  uint64_t x_;
  uint64_t y_;
  uint64_t level_;
  uint64_t hp_;
  uint64_t maxhp_;
  uint64_t mp_;
  uint64_t maxmp_;
  uint64_t exp_;
  uint64_t maxexp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Stat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Stat) */ {
 public:
  inline Stat() : Stat(nullptr) {}
  ~Stat() override;
  explicit constexpr Stat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Stat(const Stat& from);
  Stat(Stat&& from) noexcept
    : Stat() {
    *this = ::std::move(from);
  }

  inline Stat& operator=(const Stat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stat& operator=(Stat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stat& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stat* internal_default_instance() {
    return reinterpret_cast<const Stat*>(
               &_Stat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Stat& a, Stat& b) {
    a.Swap(&b);
  }
  inline void Swap(Stat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Stat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Stat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Stat& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Stat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Stat";
  }
  protected:
  explicit Stat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLevelFieldNumber = 1,
    kExpFieldNumber = 2,
    kMaxexpFieldNumber = 3,
    kHpFieldNumber = 4,
    kMaxhpFieldNumber = 5,
    kMpFieldNumber = 6,
    kMaxmpFieldNumber = 7,
  };
  // uint64 level = 1;
  void clear_level();
  uint64_t level() const;
  void set_level(uint64_t value);
  private:
  uint64_t _internal_level() const;
  void _internal_set_level(uint64_t value);
  public:

  // uint64 exp = 2;
  void clear_exp();
  uint64_t exp() const;
  void set_exp(uint64_t value);
  private:
  uint64_t _internal_exp() const;
  void _internal_set_exp(uint64_t value);
  public:

  // uint64 maxexp = 3;
  void clear_maxexp();
  uint64_t maxexp() const;
  void set_maxexp(uint64_t value);
  private:
  uint64_t _internal_maxexp() const;
  void _internal_set_maxexp(uint64_t value);
  public:

  // uint64 hp = 4;
  void clear_hp();
  uint64_t hp() const;
  void set_hp(uint64_t value);
  private:
  uint64_t _internal_hp() const;
  void _internal_set_hp(uint64_t value);
  public:

  // uint64 maxhp = 5;
  void clear_maxhp();
  uint64_t maxhp() const;
  void set_maxhp(uint64_t value);
  private:
  uint64_t _internal_maxhp() const;
  void _internal_set_maxhp(uint64_t value);
  public:

  // uint64 mp = 6;
  void clear_mp();
  uint64_t mp() const;
  void set_mp(uint64_t value);
  private:
  uint64_t _internal_mp() const;
  void _internal_set_mp(uint64_t value);
  public:

  // uint64 maxmp = 7;
  void clear_maxmp();
  uint64_t maxmp() const;
  void set_maxmp(uint64_t value);
  private:
  uint64_t _internal_maxmp() const;
  void _internal_set_maxmp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Stat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t level_;
  uint64_t exp_;
  uint64_t maxexp_;
  uint64_t hp_;
  uint64_t maxhp_;
  uint64_t mp_;
  uint64_t maxmp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class AddPlayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AddPlayer) */ {
 public:
  inline AddPlayer() : AddPlayer(nullptr) {}
  ~AddPlayer() override;
  explicit constexpr AddPlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddPlayer(const AddPlayer& from);
  AddPlayer(AddPlayer&& from) noexcept
    : AddPlayer() {
    *this = ::std::move(from);
  }

  inline AddPlayer& operator=(const AddPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPlayer& operator=(AddPlayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPlayer* internal_default_instance() {
    return reinterpret_cast<const AddPlayer*>(
               &_AddPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AddPlayer& a, AddPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(AddPlayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddPlayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddPlayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AddPlayer& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddPlayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AddPlayer";
  }
  protected:
  explicit AddPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayertypeFieldNumber = 1,
    kNameFieldNumber = 3,
    kIdFieldNumber = 2,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
  };
  // repeated .Protocol.PlayerType playertype = 1;
  int playertype_size() const;
  private:
  int _internal_playertype_size() const;
  public:
  void clear_playertype();
  private:
  ::Protocol::PlayerType _internal_playertype(int index) const;
  void _internal_add_playertype(::Protocol::PlayerType value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_playertype();
  public:
  ::Protocol::PlayerType playertype(int index) const;
  void set_playertype(int index, ::Protocol::PlayerType value);
  void add_playertype(::Protocol::PlayerType value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& playertype() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_playertype();

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 id = 2;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 x = 4;
  void clear_x();
  uint64_t x() const;
  void set_x(uint64_t value);
  private:
  uint64_t _internal_x() const;
  void _internal_set_x(uint64_t value);
  public:

  // uint64 y = 5;
  void clear_y();
  uint64_t y() const;
  void set_y(uint64_t value);
  private:
  uint64_t _internal_y() const;
  void _internal_set_y(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AddPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> playertype_;
  mutable std::atomic<int> _playertype_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  uint64_t id_;
  uint64_t x_;
  uint64_t y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Move) */ {
 public:
  inline Move() : Move(nullptr) {}
  ~Move() override;
  explicit constexpr Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Move(const Move& from);
  Move(Move&& from) noexcept
    : Move() {
    *this = ::std::move(from);
  }

  inline Move& operator=(const Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline Move& operator=(Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const Move* internal_default_instance() {
    return reinterpret_cast<const Move*>(
               &_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Move& a, Move& b) {
    a.Swap(&b);
  }
  inline void Swap(Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Move& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Move";
  }
  protected:
  explicit Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kMoveTimeFieldNumber = 4,
  };
  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 x = 2;
  void clear_x();
  uint64_t x() const;
  void set_x(uint64_t value);
  private:
  uint64_t _internal_x() const;
  void _internal_set_x(uint64_t value);
  public:

  // uint64 y = 3;
  void clear_y();
  uint64_t y() const;
  void set_y(uint64_t value);
  private:
  uint64_t _internal_y() const;
  void _internal_set_y(uint64_t value);
  public:

  // int64 move_time = 4;
  void clear_move_time();
  int64_t move_time() const;
  void set_move_time(int64_t value);
  private:
  int64_t _internal_move_time() const;
  void _internal_set_move_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t id_;
  uint64_t x_;
  uint64_t y_;
  int64_t move_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Mess final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Mess) */ {
 public:
  inline Mess() : Mess(nullptr) {}
  ~Mess() override;
  explicit constexpr Mess(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Mess(const Mess& from);
  Mess(Mess&& from) noexcept
    : Mess() {
    *this = ::std::move(from);
  }

  inline Mess& operator=(const Mess& from) {
    CopyFrom(from);
    return *this;
  }
  inline Mess& operator=(Mess&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Mess& default_instance() {
    return *internal_default_instance();
  }
  static inline const Mess* internal_default_instance() {
    return reinterpret_cast<const Mess*>(
               &_Mess_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Mess& a, Mess& b) {
    a.Swap(&b);
  }
  inline void Swap(Mess* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Mess* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Mess* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Mess>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Mess& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Mess& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Mess* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Mess";
  }
  protected:
  explicit Mess(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // string mess = 2;
  void clear_mess();
  const std::string& mess() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mess(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mess();
  PROTOBUF_NODISCARD std::string* release_mess();
  void set_allocated_mess(std::string* mess);
  private:
  const std::string& _internal_mess() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mess(const std::string& value);
  std::string* _internal_mutable_mess();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Mess)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mess_;
  uint64_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Player

// repeated .Protocol.PlayerType playertype = 1;
inline int Player::_internal_playertype_size() const {
  return playertype_.size();
}
inline int Player::playertype_size() const {
  return _internal_playertype_size();
}
inline void Player::clear_playertype() {
  playertype_.Clear();
}
inline ::Protocol::PlayerType Player::_internal_playertype(int index) const {
  return static_cast< ::Protocol::PlayerType >(playertype_.Get(index));
}
inline ::Protocol::PlayerType Player::playertype(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.Player.playertype)
  return _internal_playertype(index);
}
inline void Player::set_playertype(int index, ::Protocol::PlayerType value) {
  playertype_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.Player.playertype)
}
inline void Player::_internal_add_playertype(::Protocol::PlayerType value) {
  playertype_.Add(value);
}
inline void Player::add_playertype(::Protocol::PlayerType value) {
  _internal_add_playertype(value);
  // @@protoc_insertion_point(field_add:Protocol.Player.playertype)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
Player::playertype() const {
  // @@protoc_insertion_point(field_list:Protocol.Player.playertype)
  return playertype_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
Player::_internal_mutable_playertype() {
  return &playertype_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
Player::mutable_playertype() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.Player.playertype)
  return _internal_mutable_playertype();
}

// uint64 id = 2;
inline void Player::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t Player::_internal_id() const {
  return id_;
}
inline uint64_t Player::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.id)
  return _internal_id();
}
inline void Player::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void Player::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.id)
}

// string name = 3;
inline void Player::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Player::name() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Player::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.Player.name)
}
inline std::string* Player::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.Player.name)
  return _s;
}
inline const std::string& Player::_internal_name() const {
  return name_.Get();
}
inline void Player::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Player::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Player::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.Player.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Player::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.Player.name)
}

// uint64 x = 4;
inline void Player::clear_x() {
  x_ = uint64_t{0u};
}
inline uint64_t Player::_internal_x() const {
  return x_;
}
inline uint64_t Player::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.x)
  return _internal_x();
}
inline void Player::_internal_set_x(uint64_t value) {
  
  x_ = value;
}
inline void Player::set_x(uint64_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.x)
}

// uint64 y = 5;
inline void Player::clear_y() {
  y_ = uint64_t{0u};
}
inline uint64_t Player::_internal_y() const {
  return y_;
}
inline uint64_t Player::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.y)
  return _internal_y();
}
inline void Player::_internal_set_y(uint64_t value) {
  
  y_ = value;
}
inline void Player::set_y(uint64_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.y)
}

// uint64 level = 6;
inline void Player::clear_level() {
  level_ = uint64_t{0u};
}
inline uint64_t Player::_internal_level() const {
  return level_;
}
inline uint64_t Player::level() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.level)
  return _internal_level();
}
inline void Player::_internal_set_level(uint64_t value) {
  
  level_ = value;
}
inline void Player::set_level(uint64_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.level)
}

// uint64 hp = 7;
inline void Player::clear_hp() {
  hp_ = uint64_t{0u};
}
inline uint64_t Player::_internal_hp() const {
  return hp_;
}
inline uint64_t Player::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.hp)
  return _internal_hp();
}
inline void Player::_internal_set_hp(uint64_t value) {
  
  hp_ = value;
}
inline void Player::set_hp(uint64_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.hp)
}

// uint64 maxhp = 8;
inline void Player::clear_maxhp() {
  maxhp_ = uint64_t{0u};
}
inline uint64_t Player::_internal_maxhp() const {
  return maxhp_;
}
inline uint64_t Player::maxhp() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.maxhp)
  return _internal_maxhp();
}
inline void Player::_internal_set_maxhp(uint64_t value) {
  
  maxhp_ = value;
}
inline void Player::set_maxhp(uint64_t value) {
  _internal_set_maxhp(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.maxhp)
}

// uint64 mp = 9;
inline void Player::clear_mp() {
  mp_ = uint64_t{0u};
}
inline uint64_t Player::_internal_mp() const {
  return mp_;
}
inline uint64_t Player::mp() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.mp)
  return _internal_mp();
}
inline void Player::_internal_set_mp(uint64_t value) {
  
  mp_ = value;
}
inline void Player::set_mp(uint64_t value) {
  _internal_set_mp(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.mp)
}

// uint64 maxmp = 10;
inline void Player::clear_maxmp() {
  maxmp_ = uint64_t{0u};
}
inline uint64_t Player::_internal_maxmp() const {
  return maxmp_;
}
inline uint64_t Player::maxmp() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.maxmp)
  return _internal_maxmp();
}
inline void Player::_internal_set_maxmp(uint64_t value) {
  
  maxmp_ = value;
}
inline void Player::set_maxmp(uint64_t value) {
  _internal_set_maxmp(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.maxmp)
}

// uint64 exp = 11;
inline void Player::clear_exp() {
  exp_ = uint64_t{0u};
}
inline uint64_t Player::_internal_exp() const {
  return exp_;
}
inline uint64_t Player::exp() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.exp)
  return _internal_exp();
}
inline void Player::_internal_set_exp(uint64_t value) {
  
  exp_ = value;
}
inline void Player::set_exp(uint64_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.exp)
}

// uint64 maxexp = 12;
inline void Player::clear_maxexp() {
  maxexp_ = uint64_t{0u};
}
inline uint64_t Player::_internal_maxexp() const {
  return maxexp_;
}
inline uint64_t Player::maxexp() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.maxexp)
  return _internal_maxexp();
}
inline void Player::_internal_set_maxexp(uint64_t value) {
  
  maxexp_ = value;
}
inline void Player::set_maxexp(uint64_t value) {
  _internal_set_maxexp(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.maxexp)
}

// -------------------------------------------------------------------

// Stat

// uint64 level = 1;
inline void Stat::clear_level() {
  level_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_level() const {
  return level_;
}
inline uint64_t Stat::level() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.level)
  return _internal_level();
}
inline void Stat::_internal_set_level(uint64_t value) {
  
  level_ = value;
}
inline void Stat::set_level(uint64_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.level)
}

// uint64 exp = 2;
inline void Stat::clear_exp() {
  exp_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_exp() const {
  return exp_;
}
inline uint64_t Stat::exp() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.exp)
  return _internal_exp();
}
inline void Stat::_internal_set_exp(uint64_t value) {
  
  exp_ = value;
}
inline void Stat::set_exp(uint64_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.exp)
}

// uint64 maxexp = 3;
inline void Stat::clear_maxexp() {
  maxexp_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_maxexp() const {
  return maxexp_;
}
inline uint64_t Stat::maxexp() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.maxexp)
  return _internal_maxexp();
}
inline void Stat::_internal_set_maxexp(uint64_t value) {
  
  maxexp_ = value;
}
inline void Stat::set_maxexp(uint64_t value) {
  _internal_set_maxexp(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.maxexp)
}

// uint64 hp = 4;
inline void Stat::clear_hp() {
  hp_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_hp() const {
  return hp_;
}
inline uint64_t Stat::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.hp)
  return _internal_hp();
}
inline void Stat::_internal_set_hp(uint64_t value) {
  
  hp_ = value;
}
inline void Stat::set_hp(uint64_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.hp)
}

// uint64 maxhp = 5;
inline void Stat::clear_maxhp() {
  maxhp_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_maxhp() const {
  return maxhp_;
}
inline uint64_t Stat::maxhp() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.maxhp)
  return _internal_maxhp();
}
inline void Stat::_internal_set_maxhp(uint64_t value) {
  
  maxhp_ = value;
}
inline void Stat::set_maxhp(uint64_t value) {
  _internal_set_maxhp(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.maxhp)
}

// uint64 mp = 6;
inline void Stat::clear_mp() {
  mp_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_mp() const {
  return mp_;
}
inline uint64_t Stat::mp() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.mp)
  return _internal_mp();
}
inline void Stat::_internal_set_mp(uint64_t value) {
  
  mp_ = value;
}
inline void Stat::set_mp(uint64_t value) {
  _internal_set_mp(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.mp)
}

// uint64 maxmp = 7;
inline void Stat::clear_maxmp() {
  maxmp_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_maxmp() const {
  return maxmp_;
}
inline uint64_t Stat::maxmp() const {
  // @@protoc_insertion_point(field_get:Protocol.Stat.maxmp)
  return _internal_maxmp();
}
inline void Stat::_internal_set_maxmp(uint64_t value) {
  
  maxmp_ = value;
}
inline void Stat::set_maxmp(uint64_t value) {
  _internal_set_maxmp(value);
  // @@protoc_insertion_point(field_set:Protocol.Stat.maxmp)
}

// -------------------------------------------------------------------

// AddPlayer

// repeated .Protocol.PlayerType playertype = 1;
inline int AddPlayer::_internal_playertype_size() const {
  return playertype_.size();
}
inline int AddPlayer::playertype_size() const {
  return _internal_playertype_size();
}
inline void AddPlayer::clear_playertype() {
  playertype_.Clear();
}
inline ::Protocol::PlayerType AddPlayer::_internal_playertype(int index) const {
  return static_cast< ::Protocol::PlayerType >(playertype_.Get(index));
}
inline ::Protocol::PlayerType AddPlayer::playertype(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.AddPlayer.playertype)
  return _internal_playertype(index);
}
inline void AddPlayer::set_playertype(int index, ::Protocol::PlayerType value) {
  playertype_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.AddPlayer.playertype)
}
inline void AddPlayer::_internal_add_playertype(::Protocol::PlayerType value) {
  playertype_.Add(value);
}
inline void AddPlayer::add_playertype(::Protocol::PlayerType value) {
  _internal_add_playertype(value);
  // @@protoc_insertion_point(field_add:Protocol.AddPlayer.playertype)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
AddPlayer::playertype() const {
  // @@protoc_insertion_point(field_list:Protocol.AddPlayer.playertype)
  return playertype_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
AddPlayer::_internal_mutable_playertype() {
  return &playertype_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
AddPlayer::mutable_playertype() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.AddPlayer.playertype)
  return _internal_mutable_playertype();
}

// uint64 id = 2;
inline void AddPlayer::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t AddPlayer::_internal_id() const {
  return id_;
}
inline uint64_t AddPlayer::id() const {
  // @@protoc_insertion_point(field_get:Protocol.AddPlayer.id)
  return _internal_id();
}
inline void AddPlayer::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void AddPlayer::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.AddPlayer.id)
}

// string name = 3;
inline void AddPlayer::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& AddPlayer::name() const {
  // @@protoc_insertion_point(field_get:Protocol.AddPlayer.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddPlayer::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AddPlayer.name)
}
inline std::string* AddPlayer::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.AddPlayer.name)
  return _s;
}
inline const std::string& AddPlayer::_internal_name() const {
  return name_.Get();
}
inline void AddPlayer::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AddPlayer::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AddPlayer::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.AddPlayer.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AddPlayer::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AddPlayer.name)
}

// uint64 x = 4;
inline void AddPlayer::clear_x() {
  x_ = uint64_t{0u};
}
inline uint64_t AddPlayer::_internal_x() const {
  return x_;
}
inline uint64_t AddPlayer::x() const {
  // @@protoc_insertion_point(field_get:Protocol.AddPlayer.x)
  return _internal_x();
}
inline void AddPlayer::_internal_set_x(uint64_t value) {
  
  x_ = value;
}
inline void AddPlayer::set_x(uint64_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.AddPlayer.x)
}

// uint64 y = 5;
inline void AddPlayer::clear_y() {
  y_ = uint64_t{0u};
}
inline uint64_t AddPlayer::_internal_y() const {
  return y_;
}
inline uint64_t AddPlayer::y() const {
  // @@protoc_insertion_point(field_get:Protocol.AddPlayer.y)
  return _internal_y();
}
inline void AddPlayer::_internal_set_y(uint64_t value) {
  
  y_ = value;
}
inline void AddPlayer::set_y(uint64_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.AddPlayer.y)
}

// -------------------------------------------------------------------

// Move

// uint64 id = 1;
inline void Move::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t Move::_internal_id() const {
  return id_;
}
inline uint64_t Move::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Move.id)
  return _internal_id();
}
inline void Move::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void Move::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Move.id)
}

// uint64 x = 2;
inline void Move::clear_x() {
  x_ = uint64_t{0u};
}
inline uint64_t Move::_internal_x() const {
  return x_;
}
inline uint64_t Move::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Move.x)
  return _internal_x();
}
inline void Move::_internal_set_x(uint64_t value) {
  
  x_ = value;
}
inline void Move::set_x(uint64_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Move.x)
}

// uint64 y = 3;
inline void Move::clear_y() {
  y_ = uint64_t{0u};
}
inline uint64_t Move::_internal_y() const {
  return y_;
}
inline uint64_t Move::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Move.y)
  return _internal_y();
}
inline void Move::_internal_set_y(uint64_t value) {
  
  y_ = value;
}
inline void Move::set_y(uint64_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Move.y)
}

// int64 move_time = 4;
inline void Move::clear_move_time() {
  move_time_ = int64_t{0};
}
inline int64_t Move::_internal_move_time() const {
  return move_time_;
}
inline int64_t Move::move_time() const {
  // @@protoc_insertion_point(field_get:Protocol.Move.move_time)
  return _internal_move_time();
}
inline void Move::_internal_set_move_time(int64_t value) {
  
  move_time_ = value;
}
inline void Move::set_move_time(int64_t value) {
  _internal_set_move_time(value);
  // @@protoc_insertion_point(field_set:Protocol.Move.move_time)
}

// -------------------------------------------------------------------

// Mess

// uint64 id = 1;
inline void Mess::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t Mess::_internal_id() const {
  return id_;
}
inline uint64_t Mess::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Mess.id)
  return _internal_id();
}
inline void Mess::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void Mess::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Mess.id)
}

// string mess = 2;
inline void Mess::clear_mess() {
  mess_.ClearToEmpty();
}
inline const std::string& Mess::mess() const {
  // @@protoc_insertion_point(field_get:Protocol.Mess.mess)
  return _internal_mess();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Mess::set_mess(ArgT0&& arg0, ArgT... args) {
 
 mess_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.Mess.mess)
}
inline std::string* Mess::mutable_mess() {
  std::string* _s = _internal_mutable_mess();
  // @@protoc_insertion_point(field_mutable:Protocol.Mess.mess)
  return _s;
}
inline const std::string& Mess::_internal_mess() const {
  return mess_.Get();
}
inline void Mess::_internal_set_mess(const std::string& value) {
  
  mess_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Mess::_internal_mutable_mess() {
  
  return mess_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Mess::release_mess() {
  // @@protoc_insertion_point(field_release:Protocol.Mess.mess)
  return mess_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Mess::set_allocated_mess(std::string* mess) {
  if (mess != nullptr) {
    
  } else {
    
  }
  mess_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mess,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (mess_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    mess_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.Mess.mess)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
